Repository ecadlabs/taqueria, pull requests merged in 2022-02, with the labels that each got.

#191 Add support for specifying package version in 'taq install'
  beep.mp3
  cli.ts
  npm.ts
  package-lock.json
  package.json
  taqueria-types.ts
  taqueria-utils/taqueria-utils.ts
Labels: enhancement, good first issue

#306 Fixes #250, use flextesa_node_cors_origin environment variable to disa…
  taqueria-plugin-flextesa/docker/Dockerfile
  taqueria-plugin-flextesa/docker/package-lock.json
  taqueria-plugin-flextesa/docker/startFlextesa.ts
Labels: feature, flextesa-plugin

#301 Fixes #295, installing a plugin in the VSCode extension
  package-lock.json
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-smartpy/package.json
  taqueria-plugin-taquito/package.json
  taqueria-protocol/package.json
  taqueria-sdk/package.json
  taqueria-vscode-extension/package.json
  taqueria-vscode-extension/src/lib/pure.ts
  taqueria-vscode-extension/src/test/runTest.ts
  taqueria-vscode-extension/src/test/suite/extension.test.ts
  taqueria-vscode-extension/src/test/suite/index.ts
  taqueria-vscode-extension/tsconfig.json
Labels: bug, vscode, sdk

#280 Add roadmap page
  website/docs/roadmap.md
  website/sidebars.js
Labels: documentation

#296 Update readme.md files for npm packages
  taqueria-plugin-flextesa/README.md
  taqueria-plugin-ligo/README.md
  taqueria-plugin-smartpy/README.md
  taqueria-plugin-taquito/README.md
  taqueria-protocol/README.md
Labels: documentation, flextesa-plugin, ligo-plugin, smartpy-plugin, taquito-plugin, sdk

#240 docs: update contributor code of conduct to match repo
  website/docs/taqueria-dev/contributions.md
Labels: documentation

#230 fix margin issue #220
  website/src/css/custom.css
Labels: website

#305 Migrate Site to Google Tag Manager
  website/.gitignore
  website/docusaurus.config.js
  website/package.json
Labels: website

#242 Fixed LIGO plugin page
  website/docs/plugins/plugin-ligo.md
Labels: documentation

#308 Fixes #248, propgate storage up to VSCode
  taqueria-plugin-taquito/originate.ts
Labels: bug, vscode, taquito-plugin

#325 Fixes #315, handle parcel segfaults
  bin/build-all.sh
  bin/build-plugin.sh
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-smartpy/package.json
  taqueria-plugin-taquito/package.json
  taqueria-vscode-extension/package.json
Labels: bug

#326 Fixed type definition for Future
  taqueria-utils/taqueria-utils-types.ts
Labels: low-hanging-fruit

#331 Fixes #330, type definitions incorrect for Fluture
  cli.ts
  npm.ts
  taqueria-config.ts
  taqueria-protocol/taqueria-protocol-types.ts
  taqueria-sdk/index.ts
  taqueria-sdk/types.ts
  taqueria-types.ts
  taqueria-utils/taqueria-utils-types.ts
  taqueria-utils/taqueria-utils.ts
  tests/unit/taqueria-utils/taqueria-utils.test.ts
Labels: bug

#91 Contract Types Plugin - Initial Implementation
  .github/workflows/main.yml
  taqueria-plugin-contract-types/Readme.md
  taqueria-plugin-contract-types/example/.gitignore
  taqueria-plugin-contract-types/example/contracts/example-contract-0.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-1.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-2.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-3.json
  taqueria-plugin-contract-types/example/contracts/example-contract-4.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-5.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-6.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-7.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-8.tz
  taqueria-plugin-contract-types/example/contracts/example-contract-9.tz
  taqueria-plugin-contract-types/example/example-usage-type-utilities.ts
  taqueria-plugin-contract-types/example/example-usage.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-0.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-0.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-1.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-1.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-2.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-2.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-4.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-4.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-5.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-5.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-6.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-6.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-7.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-7.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-8.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-8.types.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-9.code.ts
  taqueria-plugin-contract-types/example/types-file/example-contract-9.types.ts
  taqueria-plugin-contract-types/example/types-file/type-aliases.ts
  taqueria-plugin-contract-types/example/types-file/type-utils.ts
  taqueria-plugin-contract-types/index.ts
  taqueria-plugin-contract-types/package.json
  taqueria-plugin-contract-types/run.ts
  taqueria-plugin-contract-types/src/cli-process.ts
  taqueria-plugin-contract-types/src/cli.ts
  taqueria-plugin-contract-types/src/generator/common.ts
  taqueria-plugin-contract-types/src/generator/contract-name.ts
  taqueria-plugin-contract-types/src/generator/contract-parser.ts
  taqueria-plugin-contract-types/src/generator/process.ts
  taqueria-plugin-contract-types/src/generator/schema-output.ts
  taqueria-plugin-contract-types/src/generator/typescript-output.ts
  taqueria-plugin-contract-types/src/taquito-contract-type-generator.ts
  taqueria-plugin-contract-types/src/type-aliases-file-content.ts
  taqueria-plugin-contract-types/src/type-aliases.ts
  taqueria-plugin-contract-types/src/type-utils-file-content.ts
  taqueria-plugin-contract-types/src/type-utils.ts
  taqueria-plugin-contract-types/tasks.ts
  taqueria-plugin-contract-types/test/generator.spec.ts
  taqueria-plugin-contract-types/tsconfig.json
Labels: feature

#311 Revert to direct GA properties
  website/docs/intro.md
  website/docusaurus.config.js
  website/package.json
Labels: website
