Repository ecadlabs/taqueria, pull requests merged in 2022-12, with the labels that each got.

#1568 Fixes #1363, Adds import-map to test:unit:deno:debug task
  tests/package.json
Labels: bug, low-hanging-fruit, testing

#1613 Refactor tasks to not fork, and always run in-process of the main execution pipeline
  analytics.ts
  cli.ts
  contracts.ts
  index.ts
  npm.ts
  taqueria-plugin-archetype/compile.ts
  taqueria-plugin-jest/contractTestTemplate.ts
  taqueria-plugin-jest/proxy.ts
  taqueria-plugin-ligo/compile.ts
  taqueria-plugin-metadata/index.ts
  taqueria-plugin-metadata/src/proxy.ts
  taqueria-protocol/TaqError.ts
  taqueria-sdk/index.ts
  taqueria-utils/taqueria-utils.ts
  task-registry.ts
  tests/e2e/data/help-contents/archetype-contents.ts
  tests/e2e/data/help-contents/contract-types-contents.ts
  tests/e2e/data/help-contents/flextesa-contents.ts
  tests/e2e/data/help-contents/help-contents.ts
  tests/e2e/data/help-contents/jest-contents.ts
  tests/e2e/taqueria-cli-other-and-mixed-plugin-commands.spec.ts
  tests/e2e/taqueria-cli-permissions.spec.ts
  tests/e2e/taqueria-plugin-archetype.spec.ts
  tests/e2e/taqueria-plugin-ipfs-pinata.spec.ts
  tests/e2e/taqueria-plugin-jest.spec.ts
  tests/e2e/taqueria-plugin-ligo.spec.ts
  tests/e2e/taqueria-plugin-taquito.spec.ts
  tests/e2e/taqueria-registered-contracts.spec.ts
  tests/e2e/utils/utils.ts
  tests/package.json
Labels: refactor

#1638 🛠️ Fix ➾ Interpretation and parsing of boolean options given to a plugin
  taqueria-sdk/index.ts
Labels: bug

#1632 🛠️ Fix ➾ Added instructions to help users verify that they have taq installed
  README.md
Labels: low-hanging-fruit, documentation

#1657 Remove redundant warning
  README.md
Labels: documentation

#1640 🛠️ Fix ➾ Remove parcel and lmdb (and indirectly clang) as dev dependencies
  .gitignore
  cspell.json
  lerna.json
  package-lock.json
  package.json
  taqueria-flextesa-manager/Dockerfile
  taqueria-flextesa-manager/package.json
  taqueria-plugin-archetype/README.md
  taqueria-plugin-archetype/_readme.eta
  taqueria-plugin-archetype/package.json
  taqueria-plugin-contract-types/README.md
  taqueria-plugin-contract-types/_readme.eta
  taqueria-plugin-contract-types/package.json
  taqueria-plugin-core/package.json
  taqueria-plugin-flextesa/README.md
  taqueria-plugin-flextesa/_readme.eta
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-ipfs-pinata/README.md
  taqueria-plugin-ipfs-pinata/_readme.eta
  taqueria-plugin-ipfs-pinata/package.json
  taqueria-plugin-jest/package.json
  taqueria-plugin-ligo/README.md
  taqueria-plugin-ligo/_readme.eta
  taqueria-plugin-ligo/common.ts
  taqueria-plugin-ligo/package.json
  taqueria-plugin-metadata/README.md
  taqueria-plugin-metadata/_readme.eta
  taqueria-plugin-metadata/package-lock.json
  taqueria-plugin-metadata/package.json
  taqueria-plugin-mock/package.json
  taqueria-plugin-smartpy/README.md
  taqueria-plugin-smartpy/_readme.eta
  taqueria-plugin-smartpy/package.json
  taqueria-plugin-taquito/README.md
  taqueria-plugin-taquito/_readme.eta
  taqueria-plugin-taquito/package.json
  taqueria-plugin-tezos-client/README.md
  taqueria-plugin-tezos-client/_readme.eta
  taqueria-plugin-tezos-client/common.ts
  taqueria-plugin-tezos-client/package.json
  taqueria-protocol/package.json
  taqueria-sdk/package.json
  taqueria-state/package.json
  taqueria-toolkit/package.json
  taqueria-vscode-extension/package.json
  taqueria-vscode-extension/src/lib/helpers.ts
  taqueria-vscode-extension/src/lib/pure.ts
  tests/e2e/taqueria-plugin-tezos-client.spec.ts
  tests/package.json
  website/docs/getting-started/installation.mdx
  website/docs/plugins/plugin-jest.mdx
  website/docs/release-notes.mdx
  website/docs/scaffolds/nft-scaffold.mdx
  website/docs/scaffolds/taco-shop.mdx
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: bug

#1645 ✨ Feature ➾ 1162, Add baking options to flextesa plugin
  .github/workflows/docker-publish.yml
  .github/workflows/main.yml
  .gitignore
  bin/build-all.sh
  bin/build-docker.sh
  deno-lock.json
  package.json
  taqueria-config.ts
  taqueria-flextesa-manager/.npmignore
  taqueria-flextesa-manager/Dockerfile
  taqueria-flextesa-manager/README.md
  taqueria-flextesa-manager/SandboxAccount.ts
  taqueria-flextesa-manager/SanitizedArgs.ts
  taqueria-flextesa-manager/index.ts
  taqueria-flextesa-manager/lib.ts
  taqueria-flextesa-manager/package.json
  taqueria-flextesa-manager/tsconfig.json
  taqueria-plugin-flextesa/README.md
  taqueria-plugin-flextesa/docker.ts
  taqueria-plugin-flextesa/index.ts
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-flextesa/proxy.ts
  taqueria-plugin-flextesa/types.ts
  taqueria-plugin-flextesa/tzkt-manager.ts
  taqueria-plugin-ligo/ligo.ts
  taqueria-plugin-tezos-client/client.ts
  taqueria-protocol/types.ts
  taqueria-sdk/index.ts
  tests/e2e/data/config-no-sandboxes.json
  tests/e2e/taqueria-cli-init.spec.ts
  tests/e2e/taqueria-plugin-flextesa.spec.ts
  tests/e2e/taqueria-plugin-ligo.spec.ts
  tests/e2e/taqueria-plugin-taquito-flextesa.spec.ts
  tests/e2e/taqueria-plugin-tezos-client.spec.ts
  tests/e2e/utils/utils.ts
  tests/package.json
  tests/unit/taqueria-utils/taqueria-utils.test.ts
Labels: feature, refactor
