Repository ecadlabs/taqueria, pull requests merged in 2023-01, with the labels that each got.

#1699 🛠️ Fix ➾ Recompute ephemeral state after installing/uninstalling a plugin
  cli.ts
  deno-lock.json
  npm.ts
  plugins.ts
  tests/e2e/taqueria-cli-e2e-smoke.spec.ts
Labels: bug

#1702 🛠️ Fix ➾ Don't generate ephemeral state twice when installing/uninstalling plugins
  cli.ts
  npm.ts
  plugins.ts
  tests/e2e/taqueria-plugin-ligo.spec.ts
Labels: bug

#1703 🛠️ Fix ➾ Use the hash of the latest protocol supported by the image as opposed to using Alpha
  package-lock.json
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-flextesa/proxy.ts
Labels: bug

#1705 🛠️ Fix ➾Updated beta warning text
  taqueria-protocol/i18n.ts
Labels: low-hanging-fruit

#1707 🧽 Chore ➾ SDK was missing tsup as a dependency
  package-lock.json
  package.json
  taqueria-plugin-archetype/package.json
  taqueria-plugin-core/package.json
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-ipfs-pinata/package.json
  taqueria-plugin-jest/package.json
  taqueria-plugin-ligo/package.json
  taqueria-plugin-metadata/package.json
  taqueria-plugin-smartpy/package.json
  taqueria-plugin-taquito/package.json
  taqueria-plugin-tezos-client/package.json
  taqueria-protocol/package.json
  taqueria-sdk/package.json
  taqueria-sdk/plugin-schema.json
Labels: dev-task

#1706 🛠️ Fix ➾ Added better error handling to the SDK
  taqueria-plugin-mock/index.js
  taqueria-sdk/index.ts
  tests/integration/plugin-mock.spec.ts
Labels: bug

#1662 🛠️ Fix ➾ Traverse directories to search for a taqueria project
  cli.ts
  deno-lock.json
  persistent-state.ts
  plugins.ts
  taqueria-config.ts
  taqueria-plugin-ligo/compile.ts
  taqueria-protocol/TaqError.ts
  taqueria-utils/taqueria-utils.ts
  tests/e2e/taqueria-cli-e2e-smoke.spec.ts
  tests/package.json
  tests/unit/plugins.test.ts
Labels: dev-task

#1731 🛠️ Fix ➾ Check Npm and Node Versions when building
  .nvmrc
  bin/build-all.sh
  taqueria-protocol/types-config-files.ts
Labels: dev-task

#1741 👷 Refactor ➾ Refactored google analytics code by separating functionality into a separate package
  analytics.ts
  cli.ts
  deno-lock.json
  import_map.json
  package-lock.json
  package.json
  taqueria-analytics/index.ts
  taqueria-analytics/package.json
  taqueria-analytics/tsconfig.json
  taqueria-analytics/types.ts
  taqueria-protocol/types.ts
  taqueria-types.ts
  task-registry.ts
Labels: feature, refactor, dev-task

#1799 🛠️ Fix ➾ execCmd should always reject with Error instance with stdout and stderr properties
  taqueria-sdk/index.ts
Labels: bug

#1805 🛠️ Fix ➾ bug introduced in toErrorWithProps. Wrong return value.
  taqueria-sdk/index.ts
Labels: bug

#1792 👷 Refactor ➾ Added V2 API for the toolkit
  taqueria-protocol/scripts/post-ts-to-zod.ts
  taqueria-protocol/types-config-files.ts
  taqueria-toolkit/TaqError.ts
  taqueria-toolkit/index.ts
  taqueria-toolkit/v1.ts
  taqueria-toolkit/v2.ts
Labels: refactor

#1810 🛠️ Fix ➾ Issue #1802, sandbox accounts transformations
  deno-lock.json
  taqueria-protocol/types-config-files.ts
  taqueria-protocol/types.ts
  taqueria-sdk/index.ts
Labels: bug

#1826 🛠️ Fix ➾ Closes #1824, transfer task not finding aliases
  taqueria-protocol/types-config-files.ts
Labels: bug

#1830 🛠️ Fix ➾ Closes #1711, update tests to assert that contextual help is working
  tests/e2e/contract-types-plugin-e2e-tests.spec.ts
  tests/e2e/taquito-plugin-e2e-tests.spec.ts
Labels: testing

#1831 🛠️ Fix ➾ Add better error handling to withTaq binary
  lerna.json
  package-lock.json
  package.json
  taqueria-analytics/package.json
  taqueria-plugin-archetype/package.json
  taqueria-plugin-contract-types/package.json
  taqueria-plugin-core/package.json
  taqueria-plugin-flextesa/package.json
  taqueria-plugin-ipfs-pinata/package.json
  taqueria-plugin-jest/package.json
  taqueria-plugin-ligo/package.json
  taqueria-plugin-metadata/package.json
  taqueria-plugin-mock/package.json
  taqueria-plugin-smartpy/package.json
  taqueria-plugin-taquito/package.json
  taqueria-plugin-tezos-client/package.json
  taqueria-protocol/package.json
  taqueria-protocol/types-config-files.ts
  taqueria-sdk/package.json
  taqueria-toolkit/bin/run.ts
  taqueria-toolkit/index.ts
  taqueria-toolkit/package.json
  taqueria-vscode-extension/package.json
  website/docs/getting-started/installation.mdx
  website/docs/release-notes.mdx
Labels: bug
